### ISSUE TITLE
why OOP?

### ISSUE THREAD

**Issue by elewaut** [israel-dryer/PyJobScraper#1]
@israel-dryer why are you doing this project in OOP ? As every site has a different approach it kind of seems to kill the utility to me since you're redefining almost every function, what am I missing here? Anyway great project!

**Comment by israel-dryer** [comment]
oh god. forgot this was out there. yeah, I would do this differently if I had time to write it over. I actually have something similar that scrapes for 40 or 50 sites, but it's structured much differently as I've learned a lot since I created this.  

I would setup 4 modules...  (application, data_access, webscrapers, utilities)

The idea is to have once class handle the database interaction, another the scraping, and another the UI component, etc...

The webscraper class is generic... it executes a scripts... pushes the data to the database class, and does a few other things... but it doesn't care what script it is running... it will iterate over a list of scripts and process them all regardless of method.

I would split up the scripts into 3 separate strategies (1. static, 2. ajax, 3. and browser automation.)

This let's me reduce the code for each website to only what I need to get the data off the page... everything else can be generalized in the webscraper class.  Same with the data handler and ui, etc...

Hope that makes sense. This project is a bad example, but OOP is handy in certain cases for reducing code duplication.
